#!/bin/bash

export CM_GIT_BRANCH="auto-update"
export CM_GIT_CHECKOUT_PATH="/root/CM/repos/local/cache/0f0d9a6869a547de/repo"
export CM_GIT_REPO_CHECKOUT="auto-update"
export CM_GIT_REPO_CHECKOUT_FOLDER="repo"
export CM_GIT_REPO_CHECKOUT_PATH="/root/CM/repos/local/cache/0f0d9a6869a547de/repo"
export CM_GIT_REPO_CURRENT_HASH="b37d72ec08372bfe1a0189a90b4dc40abb610818"
export CM_GIT_REPO_DEPTH="--depth 5"
export CM_GIT_REPO_NAME="mlperf_inference_unofficial_submissions_v5.0"
export CM_GIT_REPO_PATCH="no"
export CM_GIT_REPO_RECURSE_SUBMODULES=" --recurse-submodules"
export CM_GIT_REPO_URL="https://github.com/mlcommons/mlperf_inference_unofficial_submissions_v5.0"
export CM_MLPERF_INFERENCE_SUBMISSION_DIR="/root/CM/repos/local/cache/805d9c35109a4ec6/mlperf-inference-submission"
export CM_MLPERF_INFERENCE_SUBMISSION_VERSION="4_1-dev"
export CM_MLPERF_RESULTS_GIT_REPO_URL="https://github.com/mlcommons/mlperf_inference_unofficial_submissions_v5.0"
export CM_MLPERF_RESULTS_REPO_COMMIT_MESSAGE="Results on mlc-server"
export CM_PYTHON_BIN="python3"
export CM_PYTHON_BIN_PATH="/root/venv/cm/bin"
export CM_PYTHON_BIN_WITH_PATH="/root/venv/cm/bin/python3"
export CM_PYTHON_CACHE_TAGS="version-3.10.12,non-virtual"
export CM_PYTHON_MAJOR_VERSION="3"
export CM_PYTHON_MINOR_VERSION="10"
export CM_PYTHON_PATCH_VERSION="12"
export CM_PYTHON_VERSION="3.10.12"
export CM_QUIET="yes"
export CM_RSYNC_VERSION="rsync  version 3.2.7"
export CM_TMP_CURRENT_PATH="/root/CM/repos/local/cache/0f0d9a6869a547de/repo"
export CM_TMP_CURRENT_SCRIPT_PATH="/root/CM/repos/mlcommons@mlperf-automations/script/push-mlperf-inference-results-to-github"
export CM_TMP_CURRENT_SCRIPT_REPO_PATH="/root/CM/repos/mlcommons@mlperf-automations"
export CM_TMP_CURRENT_SCRIPT_REPO_PATH_WITH_PREFIX="/root/CM/repos/mlcommons@mlperf-automations"
export CM_TMP_CURRENT_SCRIPT_WORK_PATH="/root/CM/repos/local/cache/0f0d9a6869a547de/repo"
export CM_TMP_PIP_VERSION_STRING=""


. "/root/CM/repos/mlcommons@mlperf-automations/script/push-mlperf-inference-results-to-github/run.sh"
