graph TD
    app-mlperf-inference,d775cac873ee4231_(_reference,_rgat,_pytorch,_cuda,_valid,_r5.0-dev_default,_offline_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_rgat,_pytorch,_cuda,_valid,_r5.0-dev_default,_offline_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_reference,_rgat,_pytorch,_cuda,_valid,_r5.0-dev_default,_offline_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_reference,_rgat,_pytorch,_cuda,_valid,_r5.0-dev_default,_offline_) --> get,mlcommons,inference,src
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src
    app-mlperf-inference,d775cac873ee4231_(_reference,_rgat,_pytorch,_cuda,_valid,_r5.0-dev_default,_offline_) --> get,mlperf,inference,utils
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,cuda,_toolkit
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.numpy
    app-mlperf-inference,d775cac873ee4231_(_reference,_rgat,_pytorch,_cuda,_valid,_r5.0-dev_default,_offline_) --> get,cuda-devices,_with-pycuda
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> detect,cpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,python
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,cuda,_cudnn
    get-generic-python-lib,94b62a682bc44791_(_torch_cuda_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_torch_cuda
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,ml-model,rgat
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,dataset,mlperf,inference,igbh,_full
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> generate,user-conf,mlperf,inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,loadgen
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,mlcommons,inference,src
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,mlcommons,inference,src
    get-generic-python-lib,94b62a682bc44791_(_package.psutil_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.psutil
    get-generic-python-lib,94b62a682bc44791_(_package.colorama_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.colorama
    get-generic-python-lib,94b62a682bc44791_(_package.tqdm_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.tqdm
    get-generic-python-lib,94b62a682bc44791_(_package.requests_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.requests
    get-generic-python-lib,94b62a682bc44791_(_package.torchdata_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.torchdata
    get-generic-python-lib,94b62a682bc44791_(_package.pybind11_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.pybind11
    get-generic-python-lib,94b62a682bc44791_(_package.PyYAML_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.PyYAML
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.numpy
    get-generic-python-lib,94b62a682bc44791_(_package.pydantic_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.pydantic
    get-generic-python-lib,94b62a682bc44791_(_package.igb,_url.git+https://github.com/IllinoisGraphBenchmark/IGB-Datasets.git_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.igb,_url.git+https://github.com/IllinoisGraphBenchmark/IGB-Datasets.git
    get-generic-python-lib,94b62a682bc44791_(_package.torch-geometric,_find_links_url.https://data.pyg.org/whl/torch-2.4.0.html_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.torch-geometric,_find_links_url.https://data.pyg.org/whl/torch-2.4.0.html
    get-generic-python-lib,94b62a682bc44791_(_package.torch-scatter,_find_links_url.https://data.pyg.org/whl/torch-2.4.0.html_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.torch-scatter,_find_links_url.https://data.pyg.org/whl/torch-2.4.0.html
    get-generic-python-lib,94b62a682bc44791_(_package.torch-sparse,_find_links_url.https://data.pyg.org/whl/torch-2.4.0.html_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.torch-sparse,_find_links_url.https://data.pyg.org/whl/torch-2.4.0.html
    get-generic-python-lib,94b62a682bc44791_(_package.dgl,_find_links_url.https://data.dgl.ai/wheels/torch-2.4/cu121/repo.html_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_batch_size.2048,_cuda,_rgat,_pytorch,_offline,_fp32_) --> get,generic-python-lib,_package.dgl,_find_links_url.https://data.dgl.ai/wheels/torch-2.4/cu121/repo.html