graph TD
    app-mlperf-inference,d775cac873ee4231_(_reference,_sdxl,_pytorch,_cuda,_valid,_r5.0-dev_default,_float16,_offline_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_sdxl,_pytorch,_cuda,_valid,_r5.0-dev_default,_float16,_offline_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_reference,_sdxl,_pytorch,_cuda,_valid,_r5.0-dev_default,_float16,_offline_) --> get,python
    get-mlperf-inference-src,4b57186581024797 --> detect,os
    get-mlperf-inference-src,4b57186581024797 --> get,python3
    get-mlperf-inference-src,4b57186581024797 --> get,git,repo,_branch.master,_repo.https://github.com/mlcommons/inference
    app-mlperf-inference,d775cac873ee4231_(_reference,_sdxl,_pytorch,_cuda,_valid,_r5.0-dev_default,_float16,_offline_) --> get,mlcommons,inference,src
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_sdxl,_pytorch,_cuda,_valid,_r5.0-dev_default,_float16,_offline_) --> pull,git,repo
    get-mlperf-inference-src,4b57186581024797 --> detect,os
    get-mlperf-inference-src,4b57186581024797 --> get,python3
    get-mlperf-inference-src,4b57186581024797 --> get,git,repo,_branch.master,_repo.https://github.com/mlcommons/inference
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src
    app-mlperf-inference,d775cac873ee4231_(_reference,_sdxl,_pytorch,_cuda,_valid,_r5.0-dev_default,_float16,_offline_) --> get,mlperf,inference,utils
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,cuda,_toolkit
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.numpy
    app-mlperf-inference,d775cac873ee4231_(_reference,_sdxl,_pytorch,_cuda,_valid,_r5.0-dev_default,_float16,_offline_) --> get,cuda-devices,_with-pycuda
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> detect,cpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,python
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,cuda,_cudnn
    get-generic-python-lib,94b62a682bc44791_(_torch_cuda_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_torch_cuda
    get-generic-python-lib,94b62a682bc44791_(_torchvision_cuda_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_torchvision_cuda
    get-ml-model-stable-diffusion,22c6516b2d4d4c23_(_pytorch,_batch_size.1,_fp16_) --> download-and-extract,_rclone,_url.mlc-inference:mlcommons-inference-wg-public/stable_diffusion_fp16
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,ml-model,stable-diffusion,text-to-image,sdxl,raw,_pytorch,_batch_size.1,_fp16
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,dataset,coco2014,_validation,_full
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    get-mlperf-inference-src,4b57186581024797 --> detect,os
    get-mlperf-inference-src,4b57186581024797 --> get,python3
    get-mlperf-inference-src,4b57186581024797 --> get,git,repo,_branch.master,_repo.https://github.com/mlcommons/inference
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> generate,user-conf,mlperf,inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,loadgen
    get-mlperf-inference-src,4b57186581024797 --> detect,os
    get-mlperf-inference-src,4b57186581024797 --> get,python3
    get-mlperf-inference-src,4b57186581024797 --> get,git,repo,_branch.master,_repo.https://github.com/mlcommons/inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,mlcommons,inference,src
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,mlcommons,inference,src
    get-generic-python-lib,94b62a682bc44791_(_package.psutil_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_package.psutil
    get-generic-python-lib,94b62a682bc44791_(_package.diffusers_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_package.diffusers
    get-generic-python-lib,94b62a682bc44791_(_package.transformers_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_package.transformers
    get-generic-python-lib,94b62a682bc44791_(_package.torchvision_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_package.torchvision
    get-generic-python-lib,94b62a682bc44791_(_package.accelerate_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_package.accelerate
    get-generic-python-lib,94b62a682bc44791_(_package.torchmetrics_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_package.torchmetrics
    get-generic-python-lib,94b62a682bc44791_(_package.torch-fidelity_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_package.torch-fidelity
    get-generic-python-lib,94b62a682bc44791_(_package.open_clip_torch_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_package.open_clip_torch
    get-generic-python-lib,94b62a682bc44791_(_package.opencv-python_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_package.opencv-python
    get-generic-python-lib,94b62a682bc44791_(_package.scipy_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_package.scipy
    get-generic-python-lib,94b62a682bc44791_(_package.pandas_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> get,generic-python-lib,_package.pandas
    detect-cpu,586c8a43320142f7 --> detect,os
    benchmark-program,19f369ef47084895 --> detect,cpu
    benchmark-program-mlperf,cfff0132a8aa4018 --> benchmark-program,program
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_cuda,_batch_size.1,_sdxl,_float16_) --> benchmark-mlperf