name: Auto-Update Main Branch

on:
  push:
    branches:
      - auto-update  # Trigger workflow on commits to 'auto-update' branch

jobs:
  update-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push to protected branches

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure Git User
        run: |
          git config --global user.name mlcommons-bot
          git config --global user.email "mlcommons-bot@users.noreply.github.com"

      - name: Merge auto-update into main
        run: |
          git fetch origin auto-update:auto-update
          git merge --no-ff auto-update -m "Auto-merge updates from auto-update branch"

      - name: Push Changes to Main
        run: |
          git push origin main
