# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MLPerf inference submission checker

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CM_INDEX: "on"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v4
      with:
        path: submission_dir
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run MLPerf Inference Submission Checker
      run: |
        git clone -b dev https://github.com/mlcommons/inference
        python3 inference/tools/submission/submission_checker.py --input=./submission_dir  --skip-extra-files-in-root-check
